"
I store metadata for the OpenPonk-OntoUML-Profile package. This package contains the UML Profile definition, stereotypes, and structural constraints for the OntoUML ontology-driven conceptual modeling language.
"
Class {
	#name : 'ManifestOpenPonkOntoUMLProfile',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-OntoUML-Profile-Manifest',
	#package : 'OpenPonk-OntoUML-Profile',
	#tag : 'Manifest'
}
